# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTest < Formula
  desc "Test creating a Homebrew tap with goreleaser."
  homepage "https://github.com/cpliakas/goreleaser-test"
  version "0.1.7"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.7/goreleaser-test_0.1.7_Darwin_x86_64.tar.gz"
    sha256 "e9f63132fe67b86ed1ea8a330f38805b2d29152b6f39adc98816862f1f49971d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.7/goreleaser-test_0.1.7_Linux_x86_64.tar.gz"
    sha256 "35942749e6378b3831d10ec53d7ab2754eeb998c3df04ca07ad58549dc0c338a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.7/goreleaser-test_0.1.7_Linux_arm64.tar.gz"
    sha256 "2b2eabe6a1e65b9f556f853b7ecc6e9b0b1827b1b8e9529341680fe9a05b8775"
  end

  def install
    bin.install "goreleaser-test"
  end
end
