# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTest < Formula
  desc "Test creating a Homebrew tap with goreleaser."
  homepage "https://github.com/cpliakas/goreleaser-test"
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.3/goreleaser-test_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "739b449dcda283dff253a94e6ea6a80e63993ae2996a492d1399e161d53c20ba"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.3/goreleaser-test_0.1.3_Linux_x86_64.tar.gz"
    sha256 "82875b0f04aafd3e7278d44018983b508bd9853565cde9a2843364f9c8d2694b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/cpliakas/goreleaser-test/releases/download/v0.1.3/goreleaser-test_0.1.3_Linux_arm64.tar.gz"
    sha256 "6090e191150ae48e3ab9495e0d3b8e970e950a12bdba00c3861112243eb817bf"
  end

  def install
    bin.install "goreleaser-test"
  end

  test do
    system "#{bin}/goreleaser-test"
  end
end
